trainer:
  devices: 1
  precision: bf16-mixed

model:
  features_dim: 512
  mm_imgfe_dim: 1024
  mm_stg2fuse_dim: 512
  q_resize: 224
  db_resize: 224
  amp_dtype: bf16
  lr: 0.00001
  lrdino: 0.000001
  unfreeze_dino_mode: last2
  dino_extract_blocks: [7, 15, 23]
  utonia_pretrained: "~/.cache/utonia/ckpt/utonia.pth"
  lrutonia: 0.000001
  unfreeze_utonia_mode: last1
  utonia_extract_stages: [0, 2, 4]

data:
  dataset: kitti360
  machine: 5080
  epochs_num: 99
  train_batch_size: 2
  infer_batch_size: 12
