trainer:
  precision: 32-true

model:
  output_type: [image, vox, shallow]
  final_type: [imageorg, voxorg, shalloworg, stg2image, stg2vox]
  final_fusetype: add
  final_l2: false
  output_l2: true
  image_embed: stg2image
  cloud_embed: stg2vox
